# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1v642q0jr9br2f6mvgi5ig00azbyx3ipn8wjr4ayfm58plxjzss4";
    aarch64-linux = "04n29rsamb49zicrq3phm8k7cq7hqzdvncjxxylnx9gadr4r58iw";
    x86_64-darwin = "0wm6bdz5w8l1pcd9wgfnn3l077yl9xc4hd6xzvs6djz8cqd9gjcf";
    aarch64-darwin = "0wm6bdz5w8l1pcd9wgfnn3l077yl9xc4hd6xzvs6djz8cqd9gjcf";
  };

  urlMap = {
    x86_64-linux = "https://github.com/caarlos0/svu/releases/download/v3.0.0/svu_3.0.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/caarlos0/svu/releases/download/v3.0.0/svu_3.0.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/caarlos0/svu/releases/download/v3.0.0/svu_3.0.0_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/caarlos0/svu/releases/download/v3.0.0/svu_3.0.0_darwin_all.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "svu";
  version = "3.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./svu $out/bin/svu
  '';

  system = system;

  meta = {
    description = "Semantic Version Utility";
    homepage = "https://github.com/caarlos0/svu";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
